baseURL = 'https://lucy.hamburg'
DefaultContentLanguage = "en"
title = "Sailing Lucy"
copyright = ""

theme = 'ananke'

# SectionPagesMenu = "main"
# pagination.pagerSize = 3    # this is set low for demonstrating with dummy content. Set to a higher number
# googleAnalytics = ""
enableRobotsTXT = true
enableGitInfo = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
author = "Karsten"
site_logo = "images/lucy_logo_150.png"
description = "Sailing Contessa 32 Lucy and other follies"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-moon-gray"
text_color = "near-black"
recent_posts_number = 3
body_classes = "avenir bg-near-white"
date_format = "2. January 2006"

# editongithub = "https://github.com/karstenmueller/lucy.hamburg"

toc = true

[params.ananke.social.follow]
new_window_icon = true
networks = [
  "instagram"
]

[params.ananke.social.instagram]
username = "sailing.lucy"

# [params.repository]
# branch = 'main'
# owner = 'karstenmueller'
# repo = 'lucy.hamburg'
# service = 'GitHub'
# urlPatternEdit = 'https://github.com/%s/%s/edit/%s/%s'
# urlPatternView = 'https://github.com/%s/%s/blob/%s/%s'
