baseURL: https://lucy.hamburg
copyright: ""
theme: PaperMod
enableRobotsTXT: true
enableGitInfo: true

DefaultContentLanguage: en
defaultContentLanguageInSubdir: false

# analytics:
#   google:
#   SiteVerificationTag: "XYZabc"
