baseURL: https://lucy.hamburg
copyright: ""
#theme: blowfish
enableRobotsTXT: true
enableGitInfo: true

DefaultContentLanguage: de
defaultContentLanguageInSubdir: false

googleAnalytics: "G-KQVTEXMYSD"

# blowfish
taxonomies:
  tag: tags
  category: categories
  author: authors
  series: series

# blowfish
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

