en:
  languageName: "English"
  languageCode: "en"
  title: Sailing Lucy
  weight: 0
  menu:
    main:
      - pageRef: sailing
        name: Sailing
        weight: 2
      - pageRef: boat
        name: Boat
        weight: 3
      - pageRef: posts
        name: Posts
        weight: 4

  params:
    displayName: "EN"
    isoCode: "en"
    dateFormat: "2 Jan 2006"
    description: "Ahoy! Sailing with Contessa 32 'Lucy'"
    author:
      name: ""
      image: "images/karsten.png"
      headline: ⛵️ Ahoy! This is about sailing Contessa 32 Lucy.{{< rawhtml >}} Find Lucy's current position <a href="/en/position">here.</a>{{< /rawhtml >}}
      #bio: "Ahoy! Sailing with Contessa 32 'Lucy'"

de:
  languagename: "Deutsch"
  languageCode: "de"
  title: Segeln mit Lucy
  weight: 1
  menu:
    main:
      - pageRef: sailing
        name: Segeln
        weight: 2
      - pageRef: boat
        name: Boot
        weight: 3
      - pageRef: posts
        name: Beiträge
        weight: 4
  params:
    displayName: "DE"
    isoCode: "en"
    dateFormat: "2 Jan 2006"
    description: "⛵️ Ahoi! Segeln mit Contessa 32 'Lucy'"
    author:
      name: ""
      image: "images/karsten.png"
      headline: ⛵️ Ahoi! Segeln mit Contessa 32 'Lucy' {{< rawhtml >}} Finde Lucy's aktuelle Position <a href="/position">hier.</a>{{< /rawhtml >}}
      #bio: "⛵️ Ahoi! Segeln mit Contessa 32 'Lucy'"
      links:
        - instagram: "https://www.instagram.com/sailing.lucy"
        - email: "mailto:skipper@lucy.hamburg"
