
en:
  languageName: "üá¨üáß"
  title: Sailing Lucy
  languageNameShort: "en"
  languageCode: "en_UK"
  weight: 0
  menu:
    main:
      - url: /
        name: Home
        weight: 1
      - url: /boat/
        name: Lucy
        weight: 2
      - url: /about/
        name: About
        weight: 3

  params:
    description: "Ahoy! This is about sailing Contessa 32 Lucy"
    homeInfoParams:
      Title: "üëã Ahoi"
      Content: >
        ![Karsten](/images/karsten_small.png)

        - ‚õµÔ∏è Ahoy! This is about sailing Contessa 32 Lucy.{{< rawhtml >}} Find Lucy's current position <a href="/position">here.</a>{{< /rawhtml >}}
de:
  languagename: üá©üá™
  title: Segeln mit Lucy
  languageNameShort: "de"
  languageCode: "de_DE"
  weight: 1
  menu:
    main:
      - url: /
        name: Start
        weight: 1
      - url: /ueber/
        name: √úber
        weight: 2
      - url: /boot/
        name: Boot
        weight: 4
      - url: /posts/
        name: Beitr√§ge
        weight: 5
  params:
    description: "Dies ist mein Blog √ºber das Segeln mit Contessa 32 Lucy"
    homeInfoParams:
      Title: "üëã Ahoi"
      Content: >
        ![Karsten](/images/karsten_small.png)

        - ‚õµÔ∏è Ahoi! Hier geht es um Segeln mit Contessa 32 Lucy.{{< rawhtml >}} Finde Lucy's aktuelle Position <a href="/position">hier.</a>{{< /rawhtml >}}
