
en:
  languagename: English
  title: Sailing Lucy
  weight: 0
  menu:
    main:
      - url: /
        name: Home
        weight: 1
      - url: /about/
        name: About
        weight: 2
      - url: /boat/
        name: Boat
        weight: 4
      - url: /posts/
        name: Posts
        weight: 5

  params:
    description: "This is my blog about sailing Contessa 32 Lucy and other follies"
    homeInfoParams:
      Title: "üëã Ahoi"
      Content: >
         - ‚õµÔ∏è This is my blog about sailing Contessa 32 Lucy and other follies

         - Find Lucy on [Noforeignland](https://www.noforeignland.com/boat/lucy) or [Marinetraffic](https://www.marinetraffic.com/en/ais/details/ships/shipid:5536992/mmsi:211796970/imo:0/vessel:LUCY) and come over

de:
  languagename: Deutsch
  title: Segeln mit Lucy
  weight: 1
  menu:
    main:
      - url: /
        name: Start
        weight: 1
      - url: /ueber/
        name: √úber
        weight: 2
      - url: /boot/
        name: Boot
        weight: 4
      - url: /posts/
        name: Beitr√§ge
        weight: 5
  params:
    description: "Dies ist mein Blog √ºber segeln mit Contessa 32 Lucy und anderen Dummheiten"
    homeInfoParams:
      Title: "üëã Ahoi"
      Content: >
         - ‚õµÔ∏è Dies ist mein Blog √ºber Segeln mit Contessa 32 Lucy und anderen Dummheiten

         - Finde Lucy auf [Noforeignland](https://www.noforeignland.com/boat/lucy) oder [Marinetraffic](https://www.marinetraffic.com/en/ais/details/ships/shipid:5536992/mmsi:211796970/imo:0/vessel:LUCY) und komm vorbei

