
en:
  languagename: English
  title: Sailing Lucy
  weight: 0
  menu:
    main:
      - url: /
        name: Home
        weight: 1
      - url: /about/
        name: About
        weight: 2
      - url: /boat/
        name: Boat
        weight: 4
      - url: /posts/
        name: Posts
        weight: 5

  params:
    description: "This is my blog about sailing Contessa 32 Lucy and other follies"
    homeInfoParams:
      Title: "üëã Ahoi"
      Content: >
        ![Karsten](/images/karsten_small.png)
        ‚õµÔ∏è This is my blog about sailing Contessa 32 Lucy and other follies.
        
        - {{< rawhtml >}} Find Lucy on <a target="_blank" href="https://www.noforeignland.com/boat/lucy">Noforeignland</a>
          or <a target="_blank" href="https://www.marinetraffic.com/en/ais/details/ships/shipid:5536992/mmsi:211796970/imo:0/vessel:LUCY">Marinetraffic</a>
          {{< /rawhtml >}}
de:
  languagename: Deutsch
  title: Segeln mit Lucy
  weight: 1
  menu:
    main:
      - url: /
        name: Start
        weight: 1
      - url: /ueber/
        name: √úber
        weight: 2
      - url: /boot/
        name: Boot
        weight: 4
      - url: /posts/
        name: Beitr√§ge
        weight: 5
  params:
    description: "Dies ist mein Blog √ºber das Segeln mit Contessa 32 Lucy und andere Torheiten"
    homeInfoParams:
      Title: "üëã Ahoi"
      Content: >
        ![Karsten](/images/karsten_small.png)
        ‚õµÔ∏è Dies ist mein Blog √ºber das Segeln mit Contessa 32 Lucy und andere Torheiten

        - {{< rawhtml >}} Finde Lucy auf <a target="_blank" href="https://www.noforeignland.com/boat/lucy">Noforeignland</a>
          oder <a target="_blank" href="https://www.marinetraffic.com/en/ais/details/ships/shipid:5536992/mmsi:211796970/imo:0/vessel:LUCY">Marinetraffic</a>
          {{< /rawhtml >}}