assets:
  disableHLJS: true 
  favicon: "/favicon.ico"
  favicon16x16: "/favicon-16x16.png"
  favicon32x32: "/favicon-32x32.png"
  apple_touch_icon: "/apple-touch-icon.png"
  safari_pinned_tab: "/apple-touch-icon.png"

# blowfish
showLikes: true # requires firebase integration

colorScheme: "ocean"
defaultAppearance: "dark"
autoSwitchAppearance: "false" # force defaultAppearance
defaultBackgroundImage: "images/lucy_racing.jpg"
smartTOC: true

article:
  showHero: true
  showLikes: true # requires firebase integration
  showAuthor: false
  heroStyle: background # valid options: basic, big, background, thumbAndBackground
  showDateUpdated: true
  showEdit: true
  editURL: "https://github.com/karstenmueller/lucy.hamburg/edit/main/site/content"
  showReadingTime: false
  showTableOfContents: false # set true in articles header
  showTaxonomies: true

homepage:
  layout: background
  showRecent: true
  cardView: true

list:
  showHero: true
  heroStyle: background
  showCards: true

firebase:
  apiKey: "AIzaSyA3JMHCdB34mVo6TRzEuYa50yu5sWg6Ss0"
  authDomain: "lucy-hamburg.firebaseapp.com"
  projectId: "lucy-hamburg"
  storageBucket: "lucy-hamburg.firebasestorage.app"
  messagingSenderId: "351749291367"
  appId: "1:351749291367:web:ad4f9b34e6f690594803c2"
  measurementId: "G-4MJ3LX21HD"

buymeacoffee:
  identifier: "lucy.hamburg"
  globalWidget: true
  globalWidgetMessage: "buy me a coffee?"
  globalWidgetColor: "#b0a9c2"
