author: Karsten
# site_logo: images/lucy_logo_150.png
description: Sailing Contessa 32 Lucy and other follies
keywords: [Sailing, Contessa 32, Co32, Lucy]
env: production # to enable google analytics, opengraph, twitter-cards and schema.
images: ["images/lucy_logo.png"]
DateFormat: "January 2, 2006"
defaultTheme: auto # dark, light
ShowBreadCrumbs: true
hideFooter: true
disableScrollToTop: true
ShowPostNavLinks: true

fuseOpts: # search
    ignoreLocation: true
    keys: ["title", "permalink", "summary", "content"]

socialIcons:
    - name: email
      url: "mailto:sylucy.hamburg@gmail.com"
    - name: instagram
      url: "https://www.instagram.com/sailing.lucy/"

editPost:
  URL: "https://github.com/karstenmueller/lucy.hamburg/edit/main/site/content"
  Text: "Edit" # edit text
  appendFilePath: true # to append file path to Edit link

# minify:
#   disableXML: true
#   minifyOutput: true

assets:
  disableHLJS: true 
  favicon: "/favicon.ico"
  favicon16x16: "/favicon-16x16.png"
  favicon32x32: "/favicon-32x32.png"
  apple_touch_icon: "/apple-touch-icon.png"
  safari_pinned_tab: "/apple-touch-icon.png"

ShowBuyMeACoffeeButton: true
BuyMeACoffee:
  Slug: "lucy.hamburg"
  Text: "Buy me a coffee"
  Font: "Lato"
  Emoji: "☕️"
  ButtonColor: "f06035"
  FontColor: "000000"
  CoffeeColor: "ffffff"
  CupColor: "000000"

