name: Build and Deploy

on:
  schedule:
    - cron: "0 5 * * 1" # at 05:00 on Monday
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.154.5
      HUGO_CACHEDIR: /tmp/hugo_cache
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - uses: actions/cache@v4
        with:
          path: ${{ env.HUGO_CACHEDIR }}
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
                 
      - name: Build for publishing
        run: |
          cd site/ && 
          hugo mod get -u &&
          hugo --minify --cleanDestinationDir --enableGitInfo --gc --printPathWarnings --templateMetrics

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: public
          path: site/public

  deploy-to-github-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v7
        with:
          name: public
          path: public

      - name: List public
        run: ls -l public/

      - name: Deploy on GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

# Cloudflare is pulling from branch gh-pages
#
# deploy-to-cloudflare-pages:
#   name: Deploy to Cloudflare Pages
#   runs-on: ubuntu-latest
#   permissions:
#     contents: read
#   needs:
#     - build
#   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#   environment:
#     name: cloudflare-pages
#     url: ${{ steps.deployment.outputs.deployment-url }}

#   steps:
#     # - name: Checkout
#     #   uses: actions/checkout@v5

#     - name: Download Artifact
#       uses: actions/download-artifact@v6
#       with:
#         name: public
#         path: ./public

#     - name: Deploy to Cloudflare Pages Release
#       uses: cloudflare/wrangler-action@v3
#       id: deployment
#       with:
#         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#         accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#         command: pages deploy public --project-name=${{ secrets.CLOUDFLARE_DOMAIN_NAME }} --branch=main
